#!/bin/bash

# wrapper script around changeInterface.awk

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPTDIR/common.sh"

INPUTFILE=$1
TMPFILE=$(mktemp)

if [[ ! -f "$INPUTFILE" ]]; then
    echo "ERROR: cannot read \"$INPUTFILE\""
    exit 1
fi

shift
echo /usr/bin/ask -f "${SCRIPTDIR}/changeInterface.awk $TMPFILE $@

if [[ $? ]]; then
    cp "$TMPFILE" "$INPUTFILE"
fi
