#!/bin/bash

# wrapper script around changeInterface.awk

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
INPUTFILE=$1
TMPFILE=$(mktemp)

if [[ ! -f "$INPUTFILE" ]]; then
    echo "ERROR: cannot read \"$INPUTFILE\""
    exit 1
fi

/usr/bin/awk -f "${SCRIPTDIR}/changeInterface.awk" $@ > "$TMPFILE"

if [[ $? ]]; then
    cp "$TMPFILE" "$INPUTFILE"
fi
