#!/bin/bash

# wrapper script around changeInterface.awk

INPUTFILE=/etc/network/interfaces
TMPFILE=$(mktemp)

if [[ ! -f "$INPUTFILE" ]]; then
    echo "ERROR: cannot read \"$INPUTFILE\""
    exit 1
fi

/usr/bin/awk -f "/usr/bin/changeInterface.awk" $@ > "$TMPFILE"

if [[ $? ]]; then
    cp "$TMPFILE" "$INPUTFILE"
fi
